from sqlalchemy import Column, Integer, String, DateTime, DECIMAL, ForeignKey, Text, Boolean
from sqlalchemy.orm import relationship
from app.database import Base, beijing_now
from datetime import datetime


class ScanInboundSession(Base):
    """扫码入库会话（批次）"""
    __tablename__ = 'scan_inbound_sessions'
    id = Column(Integer, primary_key=True, index=True)
    session_no = Column(String(50), unique=True, nullable=False, comment="会话编号")
    warehouse_id = Column(Integer, ForeignKey('warehouses.id'), nullable=False, comment="仓库ID")
    operator_id = Column(Integer, ForeignKey('users.id'), nullable=False, comment="操作人")
    total_items = Column(Integer, default=0, comment="总条数")
    status = Column(String(30), default='active', comment="active, submitted, cancelled")
    created_at = Column(DateTime, default=beijing_now)
    updated_at = Column(DateTime, default=beijing_now, onupdate=beijing_now)
    operator = relationship('User', foreign_keys=[operator_id])
    warehouse = relationship('Warehouse', foreign_keys=[warehouse_id])
    inbound_orders = relationship('InboundOrder', back_populates='scan_session')


class Request(Base):
    __tablename__ = 'requests'
    id = Column(Integer, primary_key=True, index=True)
    request_no = Column(String(50), unique=True, nullable=False)
    requester_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    material_id = Column(Integer, ForeignKey('materials.id'), nullable=False)
    quantity = Column(DECIMAL(12, 2), nullable=False)
    reason = Column(String(200))
    urgency_level = Column(String(20), default='normal')
    project_code = Column(String(50), nullable=True)
    status = Column(String(30), default='pending')
    approver_id = Column(Integer, ForeignKey('users.id'))
    approved_at = Column(DateTime)
    approval_comment = Column(Text)
    leader_reviewer_id = Column(Integer, ForeignKey('users.id'), nullable=True)
    leader_reviewed_at = Column(DateTime, nullable=True)
    leader_comment = Column(Text, nullable=True)
    warehouse_manager_id = Column(Integer, ForeignKey('users.id'), nullable=True)
    outbound_at = Column(DateTime, nullable=True)
    is_synced_to_nc = Column(Boolean, default=False)
    nc_sync_time = Column(DateTime)
    created_at = Column(DateTime, default=beijing_now)
    updated_at = Column(DateTime, default=beijing_now, onupdate=beijing_now)
    requester = relationship('User', foreign_keys=[requester_id], back_populates='requests')
    approver_user = relationship('User', foreign_keys=[approver_id], back_populates='approvals')
    leader_reviewer = relationship('User', foreign_keys=[leader_reviewer_id])
    warehouse_manager = relationship('User', foreign_keys=[warehouse_manager_id])
    material = relationship('Material', back_populates='requests')
    outbound_orders = relationship('OutboundOrder', back_populates='request')


class InboundOrder(Base):
    __tablename__ = 'inbound_orders'
    id = Column(Integer, primary_key=True, index=True)
    inbound_no = Column(String(50), unique=True, nullable=False)
    inbound_type = Column(String(50), default='procurement')
    material_id = Column(Integer, ForeignKey('materials.id'), nullable=True)
    material_name_text = Column(String(200), comment='手动输入的物料名称（未匹配时）')
    specification_text = Column(String(200), comment='手动输入的规格型号（未匹配时）')
    unit_text = Column(String(50), comment='手动输入的单位（未匹配时）')
    location_id = Column(Integer, ForeignKey('locations.id'), nullable=False)
    quantity = Column(DECIMAL(12, 2), nullable=False)
    actual_quantity = Column(DECIMAL(12, 2), nullable=True, comment='实际到货数量')
    arrival_confirmed_at = Column(DateTime, nullable=True, comment='到货确认时间')
    arrival_confirmed_by = Column(Integer, ForeignKey('users.id'), nullable=True, comment='到货确认人')
    expected_arrival_date = Column(DateTime, nullable=True, comment='预计到货日期')
    supplier = Column(String(100))
    batch_info = Column(String(200))
    procurement_order_no = Column(String(50))
    source_warehouse = Column(String(50))
    reason = Column(String(200))
    status = Column(String(30), default='draft')
    assigned_role = Column(String(30), comment='分配的验收员角色，如 electrical_inspector/mechanical_inspector')
    procurement_reviewer_id = Column(Integer, ForeignKey('users.id'))
    procurement_reviewed_at = Column(DateTime)
    procurement_comment = Column(Text)
    technical_reviewer_id = Column(Integer, ForeignKey('users.id'))
    technical_reviewed_at = Column(DateTime)
    technical_comment = Column(Text)
    warehouse_manager_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    created_at = Column(DateTime, default=beijing_now)
    updated_at = Column(DateTime, default=beijing_now, onupdate=beijing_now)
    is_synced_to_nc = Column(Boolean, default=False)
    nc_sync_time = Column(DateTime)
    nc_order_no = Column(String(50))
    material = relationship('Material', back_populates='inbound_orders')
    location = relationship('Location', back_populates='inbound_orders')
    operator = relationship('User', back_populates='inbound_orders', foreign_keys=[warehouse_manager_id])
    procurement_reviewer = relationship('User', foreign_keys=[procurement_reviewer_id])
    technical_reviewer = relationship('User', foreign_keys=[technical_reviewer_id])
    arrival_confirmer = relationship('User', foreign_keys=[arrival_confirmed_by])
    source = Column(String(20), default='manual', comment="来源: manual, scan")
    scan_session_id = Column(Integer, ForeignKey('scan_inbound_sessions.id'), nullable=True)
    scan_session = relationship('ScanInboundSession', back_populates='inbound_orders')
    # 入库后审核
    inbound_reviewer_id = Column(Integer, ForeignKey('users.id'), nullable=True, comment='入库审核人')
    inbound_reviewed_at = Column(DateTime, nullable=True, comment='入库审核时间')
    inbound_review_comment = Column(Text, nullable=True, comment='入库审核意见')
    inbound_reviewer = relationship('User', foreign_keys=[inbound_reviewer_id])
    # 直接领用（不入库）
    is_direct_issue = Column(Boolean, default=False, comment='是否直接领用（不入库，直接发给领用部门）')
    direct_issue_quantity = Column(DECIMAL(12, 2), nullable=True, comment='直接领用数量（支持部分越库）')
    direct_issue_recipient = Column(String(100), nullable=True, comment='直接领用人/部门')
    direct_issue_reason = Column(String(200), nullable=True, comment='直接领用原因')
    outbound_order_id = Column(Integer, ForeignKey('outbound_orders.id'), nullable=True, comment='关联出库单ID（直接领用）')
    outbound_order = relationship('OutboundOrder', foreign_keys=[outbound_order_id], back_populates='linked_inbound_order')


class OutboundOrder(Base):
    __tablename__ = 'outbound_orders'
    id = Column(Integer, primary_key=True, index=True)
    outbound_no = Column(String(50), unique=True, nullable=False)
    outbound_type = Column(String(50), default='requisition')
    request_id = Column(Integer, ForeignKey('requests.id'))
    material_id = Column(Integer, ForeignKey('materials.id'), nullable=False)
    location_id = Column(Integer, ForeignKey('locations.id'), nullable=False)
    quantity = Column(DECIMAL(12, 2), nullable=False)
    destination_warehouse = Column(String(50))
    recipient_name = Column(String(50), comment='领用人')
    recipient_department = Column(String(50), comment='领用部门')
    reason = Column(String(200))
    warehouse_manager_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    status = Column(String(30), default='pending_approval')
    approver_id = Column(Integer, ForeignKey('users.id'))
    approved_at = Column(DateTime)
    approval_comment = Column(Text)
    created_at = Column(DateTime, default=beijing_now)
    updated_at = Column(DateTime, default=beijing_now, onupdate=beijing_now)
    is_synced_to_nc = Column(Boolean, default=False)
    nc_sync_time = Column(DateTime)
    nc_order_no = Column(String(50))
    request = relationship('Request', back_populates='outbound_orders')
    material = relationship('Material', back_populates='outbound_orders')
    location = relationship('Location', back_populates='outbound_orders')
    operator = relationship('User', back_populates='outbound_orders', foreign_keys=[warehouse_manager_id])
    approver = relationship('User', foreign_keys=[approver_id])
    outbound_items = relationship('OutboundOrderItem', back_populates='order', cascade='all, delete-orphan')
    linked_inbound_order = relationship('InboundOrder', foreign_keys='InboundOrder.outbound_order_id', back_populates='outbound_order')


class OutboundOrderItem(Base):
    __tablename__ = 'outbound_order_items'
    id = Column(Integer, primary_key=True, index=True)
    order_id = Column(Integer, ForeignKey('outbound_orders.id'), nullable=False)
    material_id = Column(Integer, ForeignKey('materials.id'), nullable=False)
    location_id = Column(Integer, ForeignKey('locations.id'), nullable=True)
    quantity = Column(DECIMAL(12, 2), nullable=False)
    batch_no = Column(String(50), nullable=True)
    created_at = Column(DateTime, default=beijing_now)
    order = relationship('OutboundOrder', back_populates='outbound_items')
    material = relationship('Material')
    location = relationship('Location')


class InventoryTransfer(Base):
    __tablename__ = 'inventory_transfers'
    id = Column(Integer, primary_key=True, index=True)
    transfer_no = Column(String(50), unique=True, nullable=False)
    material_id = Column(Integer, ForeignKey('materials.id'), nullable=False)
    from_location_id = Column(Integer, ForeignKey('locations.id'), nullable=False)
    to_location_id = Column(Integer, ForeignKey('locations.id'), nullable=False)
    quantity = Column(DECIMAL(12, 2), nullable=False)
    reason = Column(Text, nullable=False)
    warehouse_manager_id = Column(Integer, ForeignKey('users.id'), nullable=False)
    created_at = Column(DateTime, default=beijing_now)
    is_synced_to_nc = Column(Boolean, default=False)
    nc_sync_time = Column(DateTime)
    nc_order_no = Column(String(50))
    material = relationship('Material', back_populates='transfers')
    from_location = relationship('Location', foreign_keys=[from_location_id], back_populates='transfers_from')
    to_location = relationship('Location', foreign_keys=[to_location_id], back_populates='transfers_to')
    warehouse_manager = relationship('User')


